"""empty message

Revision ID: 6ae69a409841
Revises: f1b8d1e7646d
Create Date: 2023-12-12 13:28:40.693467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ae69a409841'
down_revision = 'f1b8d1e7646d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('hobby_skills', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('project_skills', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('types', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('work_history', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('project_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('hobby_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
