"""empty message

Revision ID: 7608542ebd94
Revises: 6ae69a409841
Create Date: 2023-12-12 18:13:34.347647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7608542ebd94'
down_revision = '6ae69a409841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_history_id', sa.Integer(), nullable=False))
        batch_op.drop_column('work_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('work_history_id')

    # ### end Alembic commands ###
